# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: slctl

before:
  hooks:
    - go mod tidy

builds:
  - id: slctl
    main: ./cmd/slctl
    binary: slctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    flags:
      - -a
      - -tags=netgo

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}-
      {{- .Version }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: softleader
    name: slctl
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.Tag}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^conductor'
      - Merge pull request
      - Merge branch
