before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archive:
  wrap_in_directory: false
  files:
    - LICENSE.txt
    - README.md
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
