before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/slctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
dist: _dist
archive:
  replacements:
    darwin: darwin
    linux: linux
    window: windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'