language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
script:
  - make bootstrap test
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
#  - provider: script
#    skip_cleanup: true
#    script: curl -X PUT -H "GITHUB_TOKEN:${GITHUB_TOKEN}" -F "file=@_dist/checksums.txt"  http://ci.softleader.com.tw:8081/slctl/${TRAVIS_TAG}
#    on:
#      tags: true